# Generated by Django 4.1.7 on 2023-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_app', '0003_rename_answers_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('year', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=150)),
            ],
        ),
    ]
